### ISSUE TITLE
Sapo Messenger is missing

### ISSUE THREAD

**Issue by Neustradamus** [sapo/sapo.github.com#2]
I search the sourcecode of Sapo Messenger,
Can you help me?

**Comment by Neustradamus** [comment]
Dear @sapo team, @rcarmo, @poingg, @FlavioCFOliveira, and all others,

Can you publish the source code of Sapo Messenger?

Several years after, the request is same.

Thanks in advance.

**Comment by rcarmo** [comment]
Not part of the company anymore (since 2015), so I can't help here.

**Comment by cpmachado** [comment]
It apparently closed in 2019, thus this could be closed.

Reference: https://ajuda.sapo.pt/messenger-71481

**Comment by Neustradamus** [comment]
@cpmachado: Thanks for your comment!

The service is closed but I search, I would like the SAPO Messenger source code :)

**Comment by cpmachado** [comment]
After these many years, even with the closure of the product, I'm not sure if it will ever be.
Disclaimer: I don't work for sapo

**Comment by cpmachado** [comment]
@Neustradamus I found this: https://github.com/Rubenf0xSimoes/sapo-broker
Which might be in the way you're looking for.

**Comment by rcarmo** [comment]
> @Neustradamus I found this: https://github.com/Rubenf0xSimoes/sapo-broker Which might be in the way you're looking for.

It's not. The sources for the XMPP client were removed a while after the team left.

**Comment by cpmachado** [comment]
@rcarmo I noticed just now, checking the code of the site: <https://oss.sapo.pt/about/>
 It refers to a repo: <https://github.com/sapo/sapo-messenger-for-mac>

**Comment by poingg** [comment]
As stated before by @rcarmo, the project was killed a billion light years ago. Unless it is for archaeological purposes, it makes no sense to release any of this abandonware now. Sorry, but I'll close the issue

**Comment by Neustradamus** [comment]
Why the https://github.com/sapo/sapo-messenger-for-mac has been removed?

SAPO Messenger is based on Psi, it will be nice to recover source...
